### ISSUE TITLE
Bug on "Disable button launch game"

### ISSUE THREAD

**Issue by nicolasvienot** [jeremie-gauthier/Red-Tetris#85]
There is a problem with the button "launch game".
Might be caused by server or the check in client.
To reproduce :
Get 2 players
Create a lobby with player1
Join with player2
Do ready with player2
Leave lobby with player1
Re-join lobby with player1
-> player2 has the button launch game disabled when player1 is ready and button launch game available when player1 is not ready

@jeremie-gauthier

**Comment by jeremie-gauthier** [comment]
This may be caused of the ready state check.
To enable the button I wait for a single player being not ready (which is the state of the owner at first if he don't leave) and every others must be ready.

When P1 leaves, I guess P2 become lead with its ready state set to true. Then P2 came back, set ready. And all players are ready instead of all except one.

If my intuition is good, I think a cleaner way to fix this should be to always set the owner of a lobby to ready

**Comment by nicolasvienot** [comment]
Yep, I agree with you. We should check for everyone ready. I'll check that owner will always be set to ready:true on server.
I think that when I check if everyone is ready server side, I don't check the owner.
So another solution would be to check in client that everyone is ready but the owner.

**Comment by jeremie-gauthier** [comment]
Ok, I agree with this solution.
I'll work on it !

**Comment by nicolasvienot** [comment]
Noooo
